/**
 * APEX TUNING ENGINE — FH5
 * MATRIZ DE INGENIERÍA MOTORSPORT (Master Knowledge Base)
 * Base de reglas estructurada para Forza Horizon 5
 */

import { MatrixItem, Discipline } from '../types';

export const DISCIPLINE_PROFILES: Record<
  Discipline,
  {
    name: string;
    objective: string;
    priorities: string[];
    priorityParameters: string[];
    expectedBehavior: string;
    characteristics: string;
  }
> = {
  'ROAD RACING': {
    name: 'Road Racing (Circuito Asfalto)',
    objective: 'Maximizar agarre mecánico y aerodinámico en asfalto, garantizando estabilidad en frenadas violentas y rotación neutra en vértices.',
    priorities: [
      '1. Grip mecánico y contacto neumático',
      '2. Balance lateral y neutralidad',
      '3. Estabilidad en frenada a alta velocidad',
      '4. Rotación ágil en vértice de curva',
      '5. Tracción progresiva en salida',
      '6. Velocidad punta y eficiencia de arrastre',
    ],
    priorityParameters: ['camber_front', 'arb_front', 'arb_rear', 'springs_front', 'aero_rear', 'diff_center_balance'],
    expectedBehavior: 'Dirección afilada y quirúrgica, apoyo plano sin balanceo excesivo de carrocería y tracción sin sobresaltos.',
    characteristics: 'Suspensiones rígidas, altura baja, camber negativo moderado-alto, rebote firme.',
  },
  'STREET SCENE': {
    name: 'Street Scene (Calles y Tráfico)',
    objective: 'Agilidad reactiva y tolerancia a imperfecciones del asfalto urbano, badenes y cambios de pendiente imprevistos.',
    priorities: [
      '1. Absorción de irregularidades y baches urbanos',
      '2. Reactividad de dirección y cambios rápidos de apoyo',
      '3. Tracción en asfalto frío o sucio',
      '4. Recuperación rápida tras saltos o bordillos',
      '5. Estabilidad en frenadas mixtas',
      '6. Rotación controlable',
    ],
    priorityParameters: ['bump_front', 'bump_rear', 'ride_height_front', 'arb_rear', 'tire_pressure_rear'],
    expectedBehavior: 'Carrocería dócil que no despega las ruedas en ondulaciones bruscas y dirección ágil.',
    characteristics: 'Muelles 10-15% más tolerantes que circuito, amortiguación bump ligeramente más suave, altura 1.5 cm superior.',
  },
  'DIRT': {
    name: 'Dirt Racing (Tierra y Grava)',
    objective: 'Optimizar tracción y flotación sobre superficies de baja adherencia, permitiendo deslizamiento controlado para encarar giros.',
    priorities: [
      '1. Tracción longitudinal en tierra y grava',
      '2. Recorrido útil de suspensión sin hacer tope',
      '3. Amortiguación de rebote en ondulaciones continuas',
      '4. Rotación intencionada mediante balance de masas',
      '5. Caster y toe adecuados para auto-centrado',
      '6. Diferencial bloqueado moderado para arrastre',
    ],
    priorityParameters: ['ride_height_front', 'springs_front', 'bump_front', 'diff_front_accel', 'diff_rear_accel'],
    expectedBehavior: 'Coche ágil que permite iniciar derrapes de entrada controlados y salir traccionando a cuatro ruedas.',
    characteristics: 'Presiones 23-26 psi, muelles un 35% más blandos, altura generosa, diferenciales con mayor % de aceleración.',
  },
  'CROSS COUNTRY': {
    name: 'Cross Country (Todo Terreno Extremo)',
    objective: 'Absorción masiva de impactos en aterrizajes de saltos de 50+ metros, tracción continua en barro/agua y dirección predecible.',
    priorities: [
      '1. Contacto con superficie y anti-bottoming en caídas',
      '2. Absorción masiva de energía cinética',
      '3. Tracción total AWD balanceada en lodo/arena',
      '4. Estabilidad direccional al cruzar vallas o ríos',
      '5. Control de aterrizaje sin rebote descontrolado',
      '6. Dirección predecible y auto-retorno rápido',
    ],
    priorityParameters: ['ride_height_front', 'ride_height_rear', 'rebound_front', 'bump_front', 'springs_front'],
    expectedBehavior: 'El vehículo absorbe el impacto de saltos masivos sin rebotar ni desviar la trayectoria; la suspensión utiliza todo el recorrido.',
    characteristics: 'Altura máxima o cercana al máximo, muelles progresivos suaves, compresión firme para evitar tope, rebote moderado para asentar caídas.',
  },
  'DRAG': {
    name: 'Drag (Aceleración Recta)',
    objective: 'Transferencia instantánea de masa al eje motriz, eliminación total de wheelspin inicial y relaciones de cambio cerradas.',
    priorities: [
      '1. Tracción pura longitudinal en arrancada',
      '2. Transferencia de peso al eje motriz (trasero en RWD/AWD)',
      '3. Diferencial 100% bloqueado para aceleración simétrica',
      '4. Mínima resistencia aerodinámica (Downforce 0)',
      '5. Presiones traseras bajas para máxima huella de contacto',
      '6. Marchas escalonadas al régimen de potencia máxima',
    ],
    priorityParameters: ['diff_rear_accel', 'tire_pressure_rear', 'springs_rear', 'rebound_front', 'aero_rear'],
    expectedBehavior: 'Lanzamiento explosivo sin desviación de trayectoria ni patinado inútil.',
    characteristics: 'Diferencial aceleración 100%, presiones traseras bajas (15-22 psi), muelles traseros firmes con suspensión delantera blanda en rebote.',
  },
  'DRIFT': {
    name: 'Drift (Deslizamiento Controlado)',
    objective: 'Facilidad para romper la tracción trasera a demanda, mantener ángulos de derrape extremos y control preciso del acelerador.',
    priorities: [
      '1. Iniciación rápida y sostenida de sobreviraje',
      '2. Ángulo de ataque y auto-alineación rápida de dirección',
      '3. Tracción y velocidad de avance durante el derrape',
      '4. Transición fluida de pesos entre giros enlazados',
      '5. Bloqueo predecible de ruedas traseras',
      '6. Agarre delantero direccional máximo en derrape',
    ],
    priorityParameters: ['caster', 'camber_front', 'diff_rear_accel', 'diff_rear_decel', 'tire_pressure_rear'],
    expectedBehavior: 'La cola del coche se desliza suavemente; el volante contra-volantea con rapidez gracias al caster alto y camber delantero agresivo.',
    characteristics: 'Caster a 7.0°, camber delantero entre -3.5° y -5.0°, presiones traseras altas (35-42 psi), diferencial trasero 95-100% aceleración y 90-100% deceleración.',
  },
  'CUSTOM': {
    name: 'Reglaje Personalizado',
    objective: 'Equilibrio específico configurado a medida según los requerimientos del piloto.',
    priorities: [
      '1. Balance dinámico adaptativo',
      '2. Respuesta de piloto',
      '3. Eficiencia en curva',
      '4. Estabilidad',
      '5. Frenada',
      '6. Tracción',
    ],
    priorityParameters: ['arb_front', 'arb_rear', 'springs_front', 'diff_rear_accel'],
    expectedBehavior: 'Comportamiento ajustado a los sliders de perfil de piloto.',
    characteristics: 'Configuración balanceada.',
  },
};

export const MASTER_MATRIX: MatrixItem[] = [
  {
    id: 'TIRE_PRESSURE',
    name: 'Presión de Neumáticos',
    category: 'TIRES',
    unit: 'psi',
    min: 15.0,
    max: 55.0,
    step: 0.5,
    priority: 2,
    target: 'Maximizar el parche de contacto en temperatura óptima (entre 95°C y 105°C en telemetría FH5) y regular la rigidez del flanco.',
    effectIncrease: 'Menor deformación lateral del neumático, respuesta más inmediata al volante pero menor huella de contacto máxima y calentamiento más lento.',
    effectDecrease: 'Mayor huella de contacto longitudinal y lateral, absorbe mejor irregularidades pero el neumático se sobrecalienta más rápido y la dirección se siente pastosa.',
    dependencies: ['tireCompound', 'weightKg', 'frontWeightRatio'],
    drivetrainModifiers: {
      FWD: 'Delanteros con 1.5 - 2.5 psi menos que traseros para maximizar tracción en tracción y frenada.',
      RWD: 'Traseros ajustados ligeramente más bajos (27.5 - 29.0 psi) para aumentar tracción longitudinal en aceleración.',
      AWD: 'Presiones balanceadas (delante 28.5 psi, detrás 28.0 psi) para distribución uniforme de carga térmica.',
    },
    disciplineModifiers: {
      'ROAD RACING': '28.0 - 29.5 psi caliente. Precisión óptima en asfalto liso.',
      'STREET SCENE': '27.0 - 28.5 psi para mitigar golpes en juntas de dilatación.',
      'DIRT': '24.0 - 26.5 psi para permitir que el flanco trabaje sobre piedras y rocas.',
      'CROSS COUNTRY': '21.0 - 24.5 psi para amortiguación de aterrizajes duros y tracción en fango.',
      'DRAG': 'Delanteros a 45-50 psi (mínima fricción), traseros a 15-20 psi (máxima huella).',
      'DRIFT': 'Delanteros a 28-30 psi (máximo grip direccional), traseros a 35-45 psi (facilitar rotación).',
      'CUSTOM': 'Ajuste base a 28.5 psi en ambos ejes.',
    },
    symptoms: ['Pérdida súbita de grip en curvas largas', 'Sobrecalentamiento de gomas', 'Dirección imprecisa'],
  },
  {
    id: 'CAMBER',
    name: 'Camber (Caída)',
    category: 'ALIGNMENT',
    unit: '°',
    min: -5.0,
    max: 0.0,
    step: 0.1,
    priority: 2,
    target: 'Garantizar que la banda de rodadura quede perfectamente plana contra el asfalto cuando el chasis apoya y rota con fuerza lateral en curva.',
    effectIncrease: 'Mayor agarre lateral en apoyos fuertes a expensas de frenada recta y tracción longitudinal.',
    effectDecrease: 'Mejor frenada en línea recta y tracción de salida, pero menor capacidad de giro en curvas de alta velocidad.',
    dependencies: ['suspensionAdjustable', 'frontWeightRatio', 'springs_front'],
    drivetrainModifiers: {
      FWD: 'Camber delantero negativo acusado (-1.8° a -2.5°) para contrarrestar la deformación bajo par motriz y frenada.',
      RWD: 'Camber trasero moderado (-1.0° a -1.5°) para conservar tracción al acelerar con ruedas rectas.',
      AWD: 'Balance simétrico con ligero sesgo delantero (-1.8° del / -1.3° tras).',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Delantero -1.8° a -2.2°, Trasero -1.2° a -1.6°.',
      'STREET SCENE': 'Delantero -1.6° a -1.9°, Trasero -1.1° a -1.4°.',
      'DIRT': 'Delantero -0.8° a -1.2°, Trasero -0.5° a -0.8° (en tierra no se busca ángulo excesivo).',
      'CROSS COUNTRY': 'Delantero -0.4° a -0.7°, Trasero -0.3° a -0.6° (máxima huella plana en saltos).',
      'DRAG': '0.0° en ambos ejes para que toda la banda apoye plano en aceleración recta.',
      'DRIFT': 'Delantero agresivo (-3.5° a -5.0°) para mantener agarre al contravolantear; trasero -0.5° a -1.0°.',
      'CUSTOM': 'Configuración estándar de carretera.',
    },
    symptoms: ['Subviraje a mitad de curva', 'Desgaste térmico irregular en telemetría', 'Inestabilidad en apoyo prolongado'],
  },
  {
    id: 'TOE',
    name: 'Toe (Convergencia/Divergencia)',
    category: 'ALIGNMENT',
    unit: '°',
    min: -5.0,
    max: 5.0,
    step: 0.1,
    priority: 8,
    target: 'Ajuste fino de la velocidad de entrada en curva (Turn-in) y estabilidad direccional en línea recta a alta velocidad.',
    effectIncrease: 'Toe Out (Divergencia delantera) hace la dirección extremadamente reactiva; Toe In (Convergencia trasera) estabiliza la cola en frenadas.',
    effectDecrease: 'Pérdida de estabilidad en rectas o dirección lenta y perezosa en los primeros grados de giro.',
    dependencies: ['suspensionAdjustable'],
    drivetrainModifiers: {
      FWD: 'Ligero Toe Out delantero (0.1° - 0.2°) para inducir giro inicial rápido.',
      RWD: 'Ligero Toe In trasero (-0.1° a -0.2°) para fijar el tren trasero al pisar a fondo.',
      AWD: 'Valores 0.0° neutros o muy leves para minimizar arrastre parásito.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Delantero 0.0° a 0.1° Out, Trasero 0.0° a -0.1° In.',
      'STREET SCENE': '0.0° en ambos ejes para balance.',
      'DIRT': 'Delantero 0.1° Out para inserción rápida en horquillas.',
      'CROSS COUNTRY': '0.0° neutro para evitar que baches desvíen el volante violentamente.',
      'DRAG': '0.0° absoluto para cero rozamiento lateral.',
      'DRIFT': 'Delantero 0.2° a 0.5° Out (giro instantáneo) y Trasero 0.0° o 0.1° In.',
      'CUSTOM': 'Neutro 0.0°.',
    },
    symptoms: ['Auto nervioso en recta a 250+ km/h', 'Auto perezoso al entrar a la curva'],
  },
  {
    id: 'CASTER',
    name: 'Caster (Ángulo de Avance)',
    category: 'ALIGNMENT',
    unit: '°',
    min: 1.0,
    max: 7.0,
    step: 0.1,
    priority: 8,
    target: 'Aumenta el camber dinámico al girar las ruedas y provee la fuerza de auto-centrado del volante.',
    effectIncrease: 'Más agarre al girar el volante cerrado, mayor estabilidad a alta velocidad y retorno de dirección más rápido.',
    effectDecrease: 'Dirección más blanda y ligera a bajas velocidades, pero menor estabilidad direccional.',
    dependencies: ['suspensionAdjustable'],
    drivetrainModifiers: {
      FWD: '5.5° - 6.2° para mantener tracción direccional sin endurecer la dirección.',
      RWD: '5.8° - 6.5° para agilidad y estabilidad.',
      AWD: '5.8° - 6.4° para absorción en aceleración.',
    },
    disciplineModifiers: {
      'ROAD RACING': '6.0° - 6.5°.',
      'STREET SCENE': '5.8° - 6.2°.',
      'DIRT': '5.2° - 5.8°.',
      'CROSS COUNTRY': '5.0° - 5.5°.',
      'DRAG': '7.0° para máxima estabilidad en línea recta.',
      'DRIFT': '7.0° obligatorio para auto-rotación del volante en transiciones.',
      'CUSTOM': '6.0°.',
    },
    symptoms: ['Falta de auto-centrado del volante', 'Inestabilidad direccional'],
  },
  {
    id: 'ARB',
    name: 'Barras Estabilizadoras (Anti-Roll Bars)',
    category: 'ARB',
    unit: 'escala 1.0 - 65.0',
    min: 1.0,
    max: 65.0,
    step: 0.1,
    priority: 3,
    target: 'Controlar el balance de transferencia de peso lateral entre el eje delantero y trasero en mitad de curva sin endurecer muelles.',
    effectIncrease: 'Mayor rigidez en ese eje reduce el balanceo pero disminuye el agarre relativo de ese extremo del auto.',
    effectDecrease: 'Menor rigidez permite que el chasis transfiera peso a la rueda exterior, aumentando el agarre de ese eje.',
    dependencies: ['frontArbAdjustable', 'rearArbAdjustable', 'frontWeightRatio'],
    drivetrainModifiers: {
      FWD: 'Barra delantera blanda (15.0 - 25.0) y trasera rígida (35.0 - 45.0) para obligar al eje trasero a rotar el coche.',
      RWD: 'Barra delantera moderada (20.0 - 30.0) y trasera afinada para evitar latigazos en salida.',
      AWD: 'Regla de oro FH5: Barra trasera más rígida que la delantera para eliminar el subviraje endémico de la tracción total.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Delantera 18.0 - 28.0, Trasera 24.0 - 38.0.',
      'STREET SCENE': 'Delantera 16.0 - 24.0, Trasera 22.0 - 34.0.',
      'DIRT': 'Delantera 10.0 - 18.0, Trasera 14.0 - 24.0 (barras más blandas para permitir articulación independiente).',
      'CROSS COUNTRY': 'Delantera 1.0 - 8.0, Trasera 1.0 - 10.0 (desconectar o barras ultra-suaves para máxima absorción independiente).',
      'DRAG': 'Delantera 1.0, Trasera 65.0 (elimina torsión del chasis al despegar).',
      'DRIFT': 'Delantera 35.0 - 45.0, Trasera 15.0 - 25.0 para deslizar fácilmente la parte trasera.',
      'CUSTOM': 'Balance estándar.',
    },
    symptoms: ['Subviraje en mitad de curva', 'Sobreviraje en apoyo lateral prolongado', 'Balanceo excesivo de carrocería'],
  },
  {
    id: 'SPRING',
    name: 'Muelles (Rigidez de Suspensión)',
    category: 'SPRINGS',
    unit: 'kgf/mm',
    min: 10.0,
    max: 300.0,
    step: 0.5,
    priority: 4,
    target: 'Soportar el peso estático y aerodinámico del vehículo, regulando la frecuencia de oscilación de la carrocería.',
    effectIncrease: 'Respuesta más directa en transiciones rápidas y menor cabeceo/balanceo, pero menor absorción en baches y pérdida de grip.',
    effectDecrease: 'Mayor grip mecánico en superficies imperfectas y mejor tracción, pero el chasis cabecea y puede hacer tope.',
    dependencies: ['suspensionAdjustable', 'weightKg', 'frontWeightRatio'],
    drivetrainModifiers: {
      FWD: 'Rigidez proporcional calculada: Peso del eje delantero ajustado a la frecuencia de cabeceo.',
      RWD: 'Muelles traseros calculados para soportar la transferencia de carga en aceleración sin colapsar la geometría.',
      AWD: 'Distribución matemática simétrica al % de peso exacto.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Frecuencia alta (120 - 200 kgf/mm según peso del coche).',
      'STREET SCENE': '10% a 15% más suaves que circuito.',
      'DIRT': '30% a 40% más suaves para flotar sobre grava.',
      'CROSS COUNTRY': 'Muelles progresivos blandos con amplio recorrido útil (40 - 75 kgf/mm).',
      'DRAG': 'Delanteros ultra-blandos (facilitan levantar la trompa), traseros duros como roca.',
      'DRIFT': 'Moderadamente rígidos para que el coche reaccione veloz a los impulsos.',
      'CUSTOM': 'Calculado matemáticamente.',
    },
    symptoms: ['El auto toca fondo (Bottom out)', 'Rebota descontrolado en curvas rápidas', 'Balanceo perezoso'],
  },
  {
    id: 'RIDE_HEIGHT',
    name: 'Altura de Carrocería',
    category: 'SPRINGS',
    unit: 'cm',
    min: 5.0,
    max: 35.0,
    step: 0.1,
    priority: 4,
    target: 'Bajar el centro de gravedad (CdG) sin permitir que el chasis o los amortiguadores hagan tope contra los topes de goma.',
    effectIncrease: 'Mayor recorrido de suspensión disponible y capacidad para sortear obstáculos o desniveles sin golpear los bajos.',
    effectDecrease: 'Menor transferencia de pesos y mejor efecto suelo, pero alto riesgo de tocar fondo en apoyos o saltos.',
    dependencies: ['suspensionAdjustable'],
    drivetrainModifiers: {
      FWD: 'Altura pareja o ligera inclinación delantera (-0.5 cm) para asentar masa en el tren motriz.',
      RWD: 'Altura equilibrada para no alterar la cinemática de los semiejes traseros.',
      AWD: 'Altura idéntica o +0.3 cm trasera para compensar carga dinámica en salida.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Cerca del mínimo (7.0 - 10.0 cm) que no golpee bordillos.',
      'STREET SCENE': '8.5 - 12.0 cm.',
      'DIRT': '14.0 - 20.0 cm.',
      'CROSS COUNTRY': 'Máximo disponible (22.0 - 32.0 cm) para librar peñascos y saltos monumentales.',
      'DRAG': 'Delante alta, detrás lo más baja posible.',
      'DRIFT': 'Baja (7.5 - 10.5 cm).',
      'CUSTOM': 'Estándar intermedia.',
    },
    symptoms: ['Chasis roza con el asfalto', 'Pérdida de control súbita al pasar por badenes'],
  },
  {
    id: 'REBOUND',
    name: 'Extensión de Amortiguadores (Rebound)',
    category: 'DAMPING',
    unit: 'escala 1.0 - 20.0',
    min: 1.0,
    max: 20.0,
    step: 0.1,
    priority: 4,
    target: 'Frenar la velocidad a la que el muelle se expande tras haber sido comprimido, impidiendo que el chasis rebote hacia arriba.',
    effectIncrease: 'El auto se siente asentado y pegado al suelo tras ondulaciones, pero si es excesivo la suspensión se empaqueta abajo y pierde agarre.',
    effectDecrease: 'Permite que la rueda recupere contacto rápidamente con el suelo, pero si es muy bajo el auto rebota como una pelota.',
    dependencies: ['suspensionAdjustable', 'springs_front', 'springs_rear'],
    drivetrainModifiers: {
      FWD: 'Rebound delantero firme (10.0 - 13.0) para anclar el eje tractor al asfalto.',
      RWD: 'Rebound trasero equilibrado (9.0 - 12.0).',
      AWD: 'Distribución basada en masa (delante 10.5, detrás 9.8 en coches 53% reparto).',
    },
    disciplineModifiers: {
      'ROAD RACING': '9.5 - 13.5.',
      'STREET SCENE': '8.5 - 11.5.',
      'DIRT': '6.5 - 9.0 (para rápida extensión y contacto con tierra).',
      'CROSS COUNTRY': '5.5 - 8.0 (absorbe impactos de saltos gigantes sin catapulta de retorno).',
      'DRAG': 'Delantero 1.0 (permite levantar trompa al acelerar), trasero 18.0 - 20.0.',
      'DRIFT': '9.0 - 12.0.',
      'CUSTOM': '10.0 base.',
    },
    symptoms: ['El auto rebota repetidamente tras un bache', 'Pérdida de agarre súbito en crestas'],
  },
  {
    id: 'BUMP',
    name: 'Compresión de Amortiguadores (Bump)',
    category: 'DAMPING',
    unit: 'escala 1.0 - 20.0',
    min: 1.0,
    max: 20.0,
    step: 0.1,
    priority: 4,
    target: 'Frenar la velocidad de compresión de la suspensión ante impactos o transferencias de peso dinámicas.',
    effectIncrease: 'Soporta mejor la carga inicial al frenar o entrar en curva antes de que el muelle tome el peso, pero hace el auto muy duro sobre bordillos.',
    effectDecrease: 'Pasa por encima de bordillos y baches sin perturbar el chasis, pero puede hundirse demasiado rápido en transiciones agresivas.',
    dependencies: ['suspensionAdjustable', 'rebound_front', 'rebound_rear'],
    drivetrainModifiers: {
      FWD: 'Regla de oro FH5: Bump = 50% a 70% del valor de Rebound.',
      RWD: 'Bump delantero firme y trasero permisivo para absorber la sentada al acelerar.',
      AWD: '55% - 65% del Rebound en ambos ejes.',
    },
    disciplineModifiers: {
      'ROAD RACING': '5.5 - 8.0 (aproximadamente 55-65% del Rebound).',
      'STREET SCENE': '4.8 - 6.8.',
      'DIRT': '3.8 - 5.5.',
      'CROSS COUNTRY': '4.5 - 7.0 (firme para no hacer tope en el suelo tras saltos).',
      'DRAG': 'Delantero 18.0 - 20.0, Trasero 1.0.',
      'DRIFT': '5.0 - 7.5.',
      'CUSTOM': 'Calculado a 60% de Rebound.',
    },
    symptoms: ['El auto salta hacia los lados al pisar un piano de circuito', 'Hundimiento excesivo en frenada'],
  },
  {
    id: 'AERO',
    name: 'Aerodinámica (Carga Aerodinámica / Downforce)',
    category: 'AERO',
    unit: 'kgf',
    min: 20.0,
    max: 500.0,
    step: 1.0,
    priority: 5,
    target: 'Empujar el vehículo verticalmente contra el suelo a altas velocidades para multiplicar el agarre lateral sin añadir masa inercial.',
    effectIncrease: 'Mucho más agarre lateral y estabilidad en curvas de media y alta velocidad (>140 km/h), pero genera resistencia aerodinámica (drag) reduciendo velocidad punta.',
    effectDecrease: 'Mayor velocidad punta en rectas largas, pero el coche se vuelve inestable o flota en curvas rápidas.',
    dependencies: ['frontAeroAdjustable', 'rearAeroAdjustable'],
    drivetrainModifiers: {
      FWD: 'Aero delantero alto para contrarrestar subviraje en curvones rápidos; trasero mínimo para velocidad.',
      RWD: 'Aero trasero fundamental para mantener plantadas las ruedas motrices en alta velocidad.',
      AWD: 'Equilibrio de downforce para conservar la neutralidad del chasis.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Delantera 60% - 85%, Trasera 70% - 90% del rango.',
      'STREET SCENE': 'Carga moderada para balance entre rectas y giros.',
      'DIRT': 'Carga baja a moderada (en tierra prima el grip mecánico del neumático).',
      'CROSS COUNTRY': 'Mínima o nula (los alerones sufren en aterrizajes y frenan en rectas rotas).',
      'DRAG': 'Mínima absoluta (0 kgf) para evitar resistencia al avance.',
      'DRIFT': 'Mínima para no frenar la rotación del tren trasero a velocidad.',
      'CUSTOM': 'Moderada.',
    },
    symptoms: ['El auto flota o derrapa a más de 180 km/h', 'Velocidad punta severamente limitada en rectas'],
  },
  {
    id: 'BRAKE',
    name: 'Balance y Presión de Frenos',
    category: 'BRAKES',
    unit: '%',
    min: 30.0,
    max: 70.0,
    step: 1.0,
    priority: 1,
    target: 'Distribuir el poder de frenado entre ruedas delanteras y traseras para detener el auto en la menor distancia sin desestabilizar la zaga.',
    effectIncrease: 'Más del 50% carga la frenada al tren delantero (evita trompos en frenada pero produce subviraje); más presión (>100%) aumenta la mordida.',
    effectDecrease: 'Menos del 50% carga frenada al eje trasero (ayuda a rotar el coche al entrar frenando, pero si es excesivo provoca trompo violento).',
    dependencies: ['brakesAdjustable'],
    drivetrainModifiers: {
      FWD: 'Balance 52% - 54% delantero para acompañar la transferencia de masa.',
      RWD: 'Balance 50% - 52% para estabilidad sin bloqueo.',
      AWD: 'Balance 51% - 53% delantero estándar en FH5.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Balance 51% - 53% Delantero, Presión 100%.',
      'STREET SCENE': 'Balance 51% Delantero, Presión 100%.',
      'DIRT': 'Balance 48% - 51% para permitir que la zaga empiece a deslizar en entrada a curva.',
      'CROSS COUNTRY': 'Balance 50% - 52%, Presión 95% - 100% para evitar bloqueos en irregularidades.',
      'DRAG': 'Paracaídas o frenos estándar.',
      'DRIFT': 'Balance 45% - 48% (ayuda a iniciar derrapes tocando freno).',
      'CUSTOM': 'Balance 50%, Presión 100%.',
    },
    symptoms: ['El auto se va de frente al frenar fuerte', 'La cola se descuelga y hace trompo en frenada recta'],
  },
  {
    id: 'DIFFERENTIAL',
    name: 'Diferenciales (Aceleración y Deceleración)',
    category: 'DIFFERENTIAL',
    unit: '%',
    min: 0.0,
    max: 100.0,
    step: 1.0,
    priority: 6,
    target: 'Garantizar que ambas ruedas del eje empujen juntas al acelerar, permitiendo al mismo tiempo la diferencia de rotación en curva.',
    effectIncrease: 'Mayor bloqueo al acelerar asegura tracción máxima en ambas ruedas pero produce empuje subvirador (power understeer) o sobreviraje brusco (power oversteer).',
    effectDecrease: 'Diferencial abierto permite giros suaves sin resistencia, pero la rueda interior gira en vacío perdiendo aceleración (wheelspin de una sola rueda).',
    dependencies: ['differentialAdjustable', 'drivetrain'],
    drivetrainModifiers: {
      FWD: 'Aceleración delantera 35% - 50%, Deceleración 0% - 5% para no bloquear la dirección al soltar gas.',
      RWD: 'Aceleración trasera 45% - 70% (road) para tracción progresiva; Deceleración 15% - 30% para estabilidad en retención.',
      AWD: 'Delantero Accel: 25-45%, Del Decel: 0-10%. Trasero Accel: 60-85%, Tras Decel: 20-35%. Reparto central (Rear Bias): 65% - 75% atrás para giros ágiles.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'AWD con 65-72% de potencia al eje trasero para comportamiento ágil tipo propulsión pero con tracción delantera de rescate.',
      'STREET SCENE': 'Similar a circuito con bloqueo de decel ligeramente más suave.',
      'DIRT': 'Aceleración más alta (50-70% delante, 75-90% detrás) para escupir tierra y traccionar en superficie suelta.',
      'CROSS COUNTRY': 'Aceleración delantera 60-80%, trasera 80-95%, reparto central 50/50 o 55/45 para tracción de fuerza bruta.',
      'DRAG': '100% aceleración en ambos ejes; reparto AWD 50/50.',
      'DRIFT': 'Trasero 95% - 100% aceleración y 90% - 100% deceleración para bloqueo constante.',
      'CUSTOM': 'Balance según tren motriz.',
    },
    symptoms: ['Pérdida de tracción en rueda interior al salir de curva', 'Trompo súbito al pisar a fondo saliendo del vértice'],
  },
  {
    id: 'GEARING',
    name: 'Transmisión y Relación Final',
    category: 'GEARING',
    unit: 'ratio',
    min: 0.5,
    max: 6.0,
    step: 0.01,
    priority: 7,
    target: 'Mantener el motor en su rango de potencia y torque óptimo a cualquier velocidad del circuito.',
    effectIncrease: 'Relación más corta (número mayor) da aceleración más explosiva pero menor velocidad máxima por marcha y más cambios de velocidad.',
    effectDecrease: 'Relación más larga (número menor) da marchas estiradas y mayor velocidad punta, pero menor empuje y recuperación.',
    dependencies: ['transmissionAdjustable', 'powerHp', 'torqueNm'],
    drivetrainModifiers: {
      FWD: '1ra y 2da más largas para evitar wheelspin por saturación de tracción delantera.',
      RWD: 'Escalonamiento progresivo para no sobrecargar los neumáticos traseros en marchas bajas.',
      AWD: '1ra corta para despegues inmediatos gracias a la tracción de las cuatro ruedas.',
    },
    disciplineModifiers: {
      'ROAD RACING': 'Final drive calibrado para alcanzar velocidad tope justo antes de la frenada de la recta principal.',
      'STREET SCENE': 'Marchas intermedias optimizadas para aceleración de 60 a 180 km/h.',
      'DIRT': 'Relaciones cerradas para mantener el turbo soplante y el motor alto de vueltas en horquillas lentas.',
      'CROSS COUNTRY': 'Marchas bajas con torque abundante para trepar dunas o cruzar ríos sin perder inercia.',
      'DRAG': 'Escalonamiento de 1/4 o 1/2 milla terminando al corte en la marcha más alta al cruzar la meta.',
      'DRIFT': '3ra y 4ta marcha largas y utilizables a medio régimen para sostener el ángulo sin cambios constantes.',
      'CUSTOM': 'Escalonamiento armónico estándar.',
    },
    symptoms: ['El auto se queda sin fuerza en subidas', 'Corta inyección antes de terminar las rectas'],
  },
];
